// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
    id,
    feed_id,
    url,
    title,
    description,
    published_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, DEFAULT, DEFAULT)
ON CONFLICT (url) DO NOTHING
`

type CreatePostParams struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Url         string
	Title       sql.NullString
	Description sql.NullString
	PublishedAt sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.FeedID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
	)
	return err
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT p.id, p.feed_id, p.url, p.title, p.description, p.published_at, p.created_at, p.updated_at
FROM posts p
INNER JOIN feeds f ON f.id = p.feed_id
INNER JOIN users u ON u.id = f.user_id
WHERE u.name = $1
ORDER BY f.last_fetched_at NULLS FIRST
LIMIT $2
`

type GetPostsForUserParams struct {
	Name  string
	Limit int32
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
